### ISSUE TITLE
compile in visual studio

### ISSUE THREAD

**Issue by Gurenduben** [casascius/Bitcoin-Address-Utility#18]
how do i make it a usable program?

**Comment by Gurenduben** [comment]
ive done it

**Comment by deeluna6676** [comment]
Done what?
________________________________

**Comment by Gurenduben** [comment]
i downloaded an already compiled version

**Comment by Ankithuuuu** [comment]
> i downloaded an already compiled version

Hello bro, can i get a compile version of bitcoin address utility

**Comment by Gurenduben** [comment]
> > i downloaded an already compiled version
> 
> Hello bro, can i get a compile version of bitcoin address utility

if youre tyring to get private keys, then this software cant get them

**Comment by Gurenduben** [comment]
Ive made some edits so how do i compile it?
