### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by slothbag** [casascius/Bitcoin-Address-Utility#7]
The following files are not checked in:
Base58
Base58CheckString
Bip38Base
Bip38Confirmation

You should probably remove your source control settings from the public source.. not much use to anyone else :)

**Comment by casascius** [comment]
Got it: added those files, and removed the source control settings.

I’m using a private source control server to help manage the sharing of files between this and my iPhone app.  Makes sense that I should remove references to it, given it’s a local box not on the internet.

Mike
